name: Generate AGCO RSS Feed

on:
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours at 00:00 and 12:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python agco_rss.py

      - name: Commit and push feed
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add agco_feed.xml
          git commit -m "🔄 Update AGCO RSS feed" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
